package system.transactions;

public enum TransactionOpResult {
	SUCCESS,
	
	INVALID_PAYMENT_FORMAT,
	INVALID_PAYMENT_AMOUNT,
	INVALID_PAYMENT_NOT_ENOUGH,
	
	INVALID_REF_NUM_FORMAT,
	
	INVALID_CART_INDEX,
	
	INVALID_TRANSACTION_CART_EMPTY,
	INVALID_TRANSACTION_NO_PAYMENT,
	INVALID_TRANSACTION_NO_PAY_TYPE,
	INVALID_TRANSACTION_NO_DINE_TYPE,
	INVALID_TRANSACTION_NO_REF_NUM;
}
